# This file is used to delete alerting rules in Grafana (not possible in any other way).
# The rules specified here will be deleted when Grafana starts up.
# Ensure that the UIDs match the rules you want to delete.

apiVersion: 1

deleteRules:
  - orgId: 1
    uid: rule1
  - orgId: 1
    uid: aeqiu9udpliwwc
  - orgId: 1
    uid: rule3
  
