# delete_contact_points.yaml - Grafana contact point deletion provisioning
# List receivers (by UID) to be deleted from the alerting configuration

# config file version
apiVersion: 1

# List of receivers that should be deleted
deleteContactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> unique identifier for the receiver
    uid: uid-to-delete
