# notification-policies.yaml - Grafana notification policy provisioning
# Adjust group and repeat intervals as needed for your alerting requirements

apiVersion: 1
notificationPolicies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - alertname
    group_interval: 30s
    repeat_interval: 1h
    group_wait: 10s
