apiVersion: 1
groups:
    - orgId: 1
      name: Testing
      folder: Testing
      interval: 1m
      rules:
        - uid: aeqiu9udpliwwc
          title: P_sum < 15
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P951FEA4DE68E13C5
              model:
                intervalMs: 1000
                maxDataPoints: 43200
                query: |
                    from(bucket: "pac2200")
                      |> range(start: -5m)
                      |> filter(fn: (r) =>
                        r._measurement == "pac2200-monitoring" and
                        r.source == "INST" and
                        contains(value: r._field, set: ["P_SUM"])
                      )
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: Active Power Sum is below 15
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
