# influxdb.yaml - Grafana InfluxDB datasource provisioning
# This file is rendered from a template and should not be edited manually

apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: pac2200
      tlsSkipVerify: true
    secureJsonData:
      token: my-token
