{
 "title": "Full Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Energy Counter (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_counter\" and contains(value: r._field, set: [\"energy_active_import_phase_1\", \"energy_active_import_phase_2\", \"energy_active_import_phase_3\"]))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(COUNTER)\"})"
    }
   ]
  },
  {
   "title": "Energy Counter Sum (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_counter\" and r._field == \"energy_active_import_total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(COUNTER)\"})"
    }
   ]
  },
  {
   "title": "Power Factor Sum (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_inst\" and r._field == \"power_factor_total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Power Factor Sum (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_avg1\" and r._field == \"power_factor_total_stage1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Power Factor Sum (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_avg2\" and r._field == \"power_factor_total_15min_avg\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Power Factor (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_inst\" and contains(value: r._field, set: [\"power_factor_phase_1\", \"power_factor_phase_2\", \"power_factor_phase_3\"]))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Power Factor (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_avg1\" and contains(value: r._field, set: [\"power_factor_phase_1_stage1\", \"power_factor_phase_2_stage1\", \"power_factor_phase_3_stage1\"]))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Power Factor (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_avg2\" and contains(value: r._field, set: [\"power_factor_phase_1_15min_avg\", \"power_factor_phase_2_15min_avg\", \"power_factor_phase_3_15min_avg\"]))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Reactive Power Sum (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_inst\" and r._field == \"reactive_power_q1_total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Reactive Power Sum (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"meter_avg1\" and r._field == \"reactive_power_q1_total_stage1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Reactive Power Sum (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    r._field == \"reactive_power_q1_total_15min_avg\"\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Reactive Power (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    contains(value: r._field, set: [\"reactive_power_q1_phase_1\", \"reactive_power_q1_phase_2\", \"reactive_power_q1_phase_3\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Reactive Power (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    contains(value: r._field, set: [\"reactive_power_q1_phase_1_stage1\", \"reactive_power_q1_phase_2_stage1\", \"reactive_power_q1_phase_3_stage1\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Reactive Power (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "kvoltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    contains(value: r._field, set: [\"reactive_power_q1_phase_1_15min_avg\", \"reactive_power_q1_phase_2_15min_avg\", \"reactive_power_q1_phase_3_15min_avg\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Apparent Power Sum (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    r._field == \"apparent_power_total\"\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Apparent Power Sum (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    r._field == \"apparent_power_total_stage1\"\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Apparent Power Sum (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    r._field == \"apparent_power_total_15min_avg\"\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Apparent Power (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    contains(value: r._field, set: [\"apparent_power_phase_1\", \"apparent_power_phase_2\", \"apparent_power_phase_3\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Apparent Power (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    contains(value: r._field, set: [\"apparent_power_phase_1_stage1\", \"apparent_power_phase_2_stage1\", \"apparent_power_phase_3_stage1\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Apparent Power (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    contains(value: r._field, set: [\"apparent_power_phase_1_15min_avg\", \"apparent_power_phase_2_15min_avg\", \"apparent_power_phase_3_15min_avg\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Frequency (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    r._field == \"frequency\"\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Frequency (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    r._field == \"frequency_stage1\"\n  )\n  \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Frequency (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    r._field == \"frequency_15min_avg\"\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Voltage Line-to-Line (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    contains(value: r._field, set: [\"voltage_line_12\", \"voltage_line_23\", \"voltage_line_31\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Voltage Line-to-Line (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    contains(value: r._field, set: [\"voltage_line_12_stage1\", \"voltage_line_23_stage1\", \"voltage_line_31_stage1\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Voltage Line-to-Line (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    contains(value: r._field, set: [\"voltage_line_12_15min_avg\", \"voltage_line_23_15min_avg\", \"voltage_line_31_15min_avg\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Active Power Sum (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    contains(value: r._field, set: [\"active_power_total\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Active Power Sum (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    contains(value: r._field, set: [\"active_power_total_stage1\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Active Power Sum (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    contains(value: r._field, set: [\"active_power_total_15min_avg\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Active Power (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    contains(value: r._field, set: [\"active_power_phase_1\", \"active_power_phase_2\", \"active_power_phase_3\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Active Power (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    contains(value: r._field, set: [\"active_power_phase_1_stage1\", \"active_power_phase_2_stage1\", \"active_power_phase_3_stage1\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Active Power (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    contains(value: r._field, set: [\"active_power_phase_1_15min_avg\", \"active_power_phase_2_15min_avg\", \"active_power_phase_3_15min_avg\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Voltage (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    contains(value: r._field, set: [\"voltage_phase_1\", \"voltage_phase_2\", \"voltage_phase_3\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Voltage (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    contains(value: r._field, set: [\"voltage_phase_1_stage1\", \"voltage_phase_2_stage1\", \"voltage_phase_3_stage1\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Voltage (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 273 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    contains(value: r._field, set: [\"voltage_phase_1_15min_avg\", \"voltage_phase_2_15min_avg\", \"voltage_phase_3_15min_avg\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  },
  {
   "title": "Current (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 281 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_inst\" and\n    contains(value: r._field, set: [\"current_phase_1\", \"current_phase_2\", \"current_phase_3\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Current (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 289 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg1\" and\n    contains(value: r._field, set: [\"current_phase_1_stage1\", \"current_phase_2_stage1\", \"current_phase_3_stage1\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG1)\"})"
    }
   ]
  },
  {
   "title": "Current (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 297 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"meter_avg2\" and\n    contains(value: r._field, set: [\"current_phase_1_15min_avg\", \"current_phase_2_15min_avg\", \"current_phase_3_15min_avg\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n|> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(AVG2)\"})"
    }
   ]
  }
 ]
}