{
 "title": "PAC2200 Main Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Energy Counter Sum (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200_counter\" and\n    contains(value: r._field, set: [\"ACT_ENERGY_IMPORT_T1_TOTAL\"])\n  )\n  \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(COUNTER)\"})"
    }
   ]
  },
  {
   "title": "Active Power Sum (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200\" and\n    contains(value: r._field, set: [\"P_SUM\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Voltage (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200\" and\n    contains(value: r._field, set: [\"V_L1\", \"V_L2\", \"V_L3\"])\n  )\n\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  },
  {
   "title": "Current (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200\" and\n    contains(value: r._field, set: [\"I_L1\", \"I_L2\", \"I_L3\"])\n  )\n  \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n|> rename(columns: {_field: \"phase\", _value: \"(INST)\"})"
    }
   ]
  }
 ]
}