{
 "title": "PAC2200",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active Power (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"COUNTER\" and\n    contains(value: r._field, set: [\n      \"ACT_ENERGY_IMPORT_T1_L1\", \n      \"ACT_ENERGY_IMPORT_T1_L2\", \n      \"ACT_ENERGY_IMPORT_T1_L3\"\n    ])\n  )\n"
    }
   ]
  },
  {
   "title": "Power Factor (inst sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    r._field == \"PF_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Power Factor (10s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    r._field == \"PF_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Power Factor (900s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    r._field == \"PF_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Power Factor (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"PF_L1\", \"PF_L2\", \"PF_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power Factor (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"PF_L1\", \"PF_L2\", \"PF_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power Factor (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"PF_L1\", \"PF_L2\", \"PF_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Reactive Power (inst sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    r._field == \"VARQ1_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Reactive Power (10s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    r._field == \"VARQ1_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Reactive Power (900s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    r._field == \"VARQ1_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Reactive Power (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"VARQ1_L1\", \"VARQ1_L2\", \"VARQ1_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Reactive Power (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"VARQ1_L1\", \"VARQ1_L2\", \"VARQ1_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Reactive Power (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"VARQ1_L1\", \"VARQ1_L2\", \"VARQ1_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Apparent Power (inst sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    r._field == \"VA_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Apparent Power (10s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    r._field == \"VA_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Apparent Power (900s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    r._field == \"VA_SUM\"\n  )\n"
    }
   ]
  },
  {
   "title": "Apparent Power (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"VA_L1\", \"VA_L2\", \"VA_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Apparent Power (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"VA_L1\", \"VA_L2\", \"VA_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Apparent Power (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"VA_L1\", \"VA_L2\", \"VA_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Frequency (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    r._field == \"FREQ\"\n  )\n"
    }
   ]
  },
  {
   "title": "Frequency (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    r._field == \"FREQ\"\n  )\n"
    }
   ]
  },
  {
   "title": "Frequency (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    r._field == \"FREQ\"\n  )\n"
    }
   ]
  },
  {
   "title": "Voltage Line-to-Line (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"V_L12\", \"V_L23\", \"V_L31\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Voltage Line-to-Line (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"V_L12\", \"V_L23\", \"V_L31\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Voltage Line-to-Line (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"V_L12\", \"V_L23\", \"V_L31\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power (inst sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"P_SUM\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power (10s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"P_SUM\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power (900s average sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"P_SUM\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"P_L1\", \"P_L2\", \"P_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"P_L1\", \"P_L2\", \"P_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Power (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"P_L1\", \"P_L2\", \"P_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Voltage (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"V_L1\", \"V_L2\", \"V_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Voltage (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"V_L1\", \"V_L2\", \"V_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Voltage (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"V_L1\", \"V_L2\", \"V_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Amperage (inst)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"INST\" and\n    contains(value: r._field, set: [\"I_L1\", \"I_L2\", \"I_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Amperage (10s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG1\" and\n    contains(value: r._field, set: [\"I_L1\", \"I_L2\", \"I_L3\"])\n  )\n"
    }
   ]
  },
  {
   "title": "Amperage (900s average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
   "targets": [
    {
     "query": "from(bucket: \"pac2200\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pac2200-monitoring\" and\n    r.source == \"AVG2\" and\n    contains(value: r._field, set: [\"I_L1\", \"I_L2\", \"I_L3\"])\n  )\n"
    }
   ]
  }
 ]
}